performance/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

performance/dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    # Emergency
    path('emergency/create/',views.dashboard_emergency_create,name='emergencycreate'),
    path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # Family
    path('family/create/',views.dashboard_family_create,name='familycreate'),
    path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    #Bank
    path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    # BIRTHDAY ROUTE
    path('birthdays/all/',views.birthday_this_month,name='birthdays'),



]

performance/setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from taskmanager.views.tasks import send_push,view_push
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),  # change url in production --> Actservsuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('task-master/', include('taskmanager.urls')),
    # path('',view_push, name='view_push'),
    path('send_push', send_push, name='send_push'),
    path('reports/', include('reports.urls', namespace='reports')),
    path('webpush/', include('webpush.urls')),
    path('select2/', include('django_select2.urls')),
]

urlpatterns += [
    path('pams_system/', include('pams_system.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
admin.site.site_header = 'Actserv ADMINISTRATION'

performance/templates/_modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

performance/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title> Actserv HR - welcome page</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />
  <!-- Bootstrap core CSS     -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Anton|Russo+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alice" rel="stylesheet">
  



</head>
<body>

    <style type="text/css">
       body{
          position: relative;
          background:rgba(248, 151, 52, 1);
          background:url("static/img/office-1.jpg");
          background-size:cover;
          opacity:0.6

        }

        
        a{
                font-variant: petite-caps;
                font-weight: 100;
                font-size: 16px;
        }


        .navbar-brand{
          font-variant: petite-caps;
          font-family: 'Luckiest Guy', cursive;
          font-weight: 600;
          font-size: 3.1rem;
          color: #e4a530;
          text-shadow:1px 2px 1px rgba(0,0,0,0.2);

        }


        h2{
          font-family: 'Alice', serif;
          color: gold;
          font-size: 4.9rem;


        }



        p{
          font-variant: small-caps;
          color: #cecece;

        }

        p span{
          color: #a5a5a5;
          font-weight: bold;
        }

        span.icon{
          font-size: 15px;
        }

        .content{
          position: relative;
          height: 100vh;
        }

        .sub-title{
        vertical-align: -webkit-baseline-middle;
        font-size: 12px !important;
        font-family: 'Luckiest Guy', cursive;
        }

        .back-link{
          color: #fff;
          font-size: 2.6rem;
          font-weight: 900;
          transition: all 400ms ease-in-out;
        }

        .back-link:hover{
          color: #fff;
          font-size: 2.8rem;
          transition: all 400ms ease-in-out;
        }

        .container-centered-items{
          position: absolute;
          top: 50%;
          left: 0;
          right: 0;
        }

    </style>

    <!--CONTENTS-->
 
    <section class="content">
            <!-- Navigation -->
                <nav class="navbar navbar-default">
                      <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                          {% if request.user.is_authenticated %}
                          <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">Actserv <span class="sub-title">HRM</span></a>
                          {% else %}
                          <a class="navbar-brand" href="/">Actserv <span>HRM</span></a>
                          {% endif %}
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav">
                            <li class=""><a href="http://www.Actservgroup.com/" target="_blank">Actserv site <span class="sr-only">(current)</span></a></li>
                            <li><a href="http://webmail.Actservgroup.com/" target="_blank">Actserv mail</a></li>
                          </ul>
                          <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                          </ul>
                        </div><!-- /.navbar-collapse -->
                      </div><!-- /.container-fluid -->
                </nav>
            <!-- /Naivagtion -->

            <div class="container-fluid container-centered-items">
                <section class="row">
                  <section class="">
                     <section class="col col-lg-12 text-center">
                        <div class="center-me-please">
                            <h2>Actserv EMPLOYEE MANAGEMENT SYSTEM</h2>
                            <p>This Application helps Actserv employees view their <span>profile</span>,apply for <span>leave</span> and get notification on <span>birthdays</span> <span>tasks</span> <span class="icon">😍🎂😘😍 ...</span></p>
                            <a class="btn btn-lg btn-success" style="width:50%;text-decoration: none;color:white;" href="{% url 'accounts:login' %}"
                                       style="text-decoration: none;color:#444140;">
                                        login
                            </a>
                        </div>
                     </section>
                  </section>
              </section>
            </div>
     </section> <!-- /content -->
    <div>
       {% if request.user.is_authenticated %}
                    <p style="position: absolute;bottom: 0;"><a href="{{request.META.HTTP_REFERER|escape}}" class="back-link" title="back to previous page"><i class="pe-7s-back-2"></i></a></p>
       {% endif %}
    </div>

</body>

    <!--   Core JS Files   -->
  <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
  


	<script type="text/javascript">
  
  
	</script>
 

</html>