performance/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

performance/setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from taskmanager.views.tasks import send_push,view_push
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),  # change url in production --> Actservsuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('task-master/', include('taskmanager.urls')),
    # path('',view_push, name='view_push'),
    path('send_push', send_push, name='send_push'),
    path('reports/', include('reports.urls', namespace='reports')),
    path('webpush/', include('webpush.urls')),
    path('select2/', include('django_select2.urls')),
]

urlpatterns += [
    path('pams_system/', include('pams_system.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
admin.site.site_header = 'Actserv ADMINISTRATION'

performance/taskmanager/urls.py
"""Task Manager URL Configuration

"""
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from taskmanager import views

# from . import views

app_name = 'taskmanager'

urlpatterns = [
    path('', views.index, name='index'),
    path('teams/<int:team_id>/', views.team_detail, name='team_detail'),
    path('teams/create/', views.team_create, name='team_create'),
    path('teams/<int:team_id>/remove-member/', views.team_remove_member, name='team_remove_member'),
    path('teams/<int:team_id>/add-member/', views.team_add_member, name='team_add_member'),
    path('teams/<int:team_id>/delete/', views.team_delete, name='team_delete'),
    path('my-tasks/', views.tasks, name='task_my_tasks'),
    path('my-completed-tasks/', views.completed_tasks, name='task_completed_tasks'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/edit/', views.task_edit, name='task_edit'),
    path('tasks/<int:task_id>/comment/', views.task_comment, name='task_comment'),
    path('tasks/<int:task_id>/accept/', views.task_accept, name='task_accept'),
    path('tasks/<int:task_id>/mark-completed/', views.task_mark_completed, name='task_mark_completed'),
    path('tasks/<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('tasks/search/', views.task_search, name='task_search'),
    # path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    # path('logout/', views.logout, name='logout'),
]

# urlpatterns += [
# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

performance/taskmanager/models.py
from django.db import models

performance/taskmanager/models/tasks.py
import datetime

from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

# Get user model defined in settings.AUTH_USER_MODEL
# Better to call get_user_model in pluggable app instead of imporing User from django.contrib.auth.models
UserModel = get_user_model()


class Team(models.Model):
    """
    Not using Django's built-in Group model because we want
    to save the creater of team.
    """
    name = models.CharField(max_length=50)
    desc = models.TextField(default='', max_length=1024, blank=True)
    leader = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='leading_teams')
    members = models.ManyToManyField(UserModel)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("taskmanager:team_detail", kwargs={"team_id": self.id})

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Teams"


class Task(models.Model):
    title = models.CharField(max_length=50)
    desc = models.TextField(default="", max_length=1024, blank=True)
    client_code = models.TextField(default="", max_length=1024, blank=True)
    client_name = models.TextField(default="", max_length=1024, blank=True)
    STATUS_CHOICES = (
        ('PLAN', 'Planned'),
        ('PROG', 'In Progress'),
        ('COMP', 'Completed')
    )
    status = models.CharField(max_length=4, choices=STATUS_CHOICES, default='PLAN')

    creator = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='created_tasks')

    # A task can be assigned to one or many users
    assigned_to = models.ManyToManyField(UserModel, help_text="Press ctrl to select multiple")

    team = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True)
    planned_date = models.DateField(auto_now_add=True)
    accepted_date = models.DateField(null=True, blank=True)
    accepted_by = models.ForeignKey(UserModel, on_delete=models.SET_NULL, null=True, related_name='accepted_tasks',
                                    blank=True)
    due_date = models.DateField()
    revised_due_date = models.DateField(null=True, blank=True)
    date_accepted = models.DateField(null=True, blank=True)
    completed_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("taskmanager:task_detail", kwargs={"task_id": self.id})

    # Has due date for an instance of this object passed?
    def is_overdated(self):
        """Returns whether the Tasks's due date has passed or not."""
        if self.due_date and datetime.date.today() > self.due_date:
            return True
        else:
            return False

    class Meta:
        ordering = ["planned_date"]
        verbose_name_plural = "Tasks"


class Comment(models.Model):
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    comment_datetime = models.DateTimeField(auto_now_add=True)
    body = models.TextField()

    def snippet(self):
        """
        Returns a short version of comment body with auther's username as prefix
        """
        return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:36])

    def __str__(self):
        return self.snippet()

    class Meta:
        ordering = ["-comment_datetime"]

performance/taskmanager/views/index.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from taskmanager.models import Team

@require_http_methods(["GET"])
def index(request):
    if request.user.is_authenticated:
        teams = request.user.team_set.all()
        return render(
            request,
            'taskmanager/index.html',
            {'user' : request.user, 'teams' : teams}
        )
    else:
        return render(request, 'taskmanager/index.html', {'user' : request.user})

performance/taskmanager/views/search.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.views.decorators.http import require_http_methods

from taskmanager.models import Task

@login_required
@require_http_methods(["GET"])
def task_search(request):
    """
    Search for tasks user has permission to see.
    """
    query_string = ""
    found_tasks = None
    if ("q" in request.GET) and request.GET["q"].strip():
        query_string = request.GET["q"]

        found_tasks = Task.objects.filter(
            (Q(title__icontains=query_string) | Q(desc__icontains=query_string)) &
            (Q(creator=request.user) | Q(assigned_to=request.user))
        ).distinct()
    else:
        messages.error(request, "Missing search parameter!")

    context = {"query_string": query_string, "found_tasks": found_tasks}
    return render(request, "taskmanager/task_search_results.html", context)

performance/taskmanager/views/teams.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods

from taskmanager.models import Team

UserModel = get_user_model()

@login_required
@require_http_methods(["GET", "POST"])
def team_create(request):
    """
    Any authenticated user can create team
    creator is leader of the team.
    """
    if request.method == 'POST':
        if request.POST.get('team_name'):
            team_name = request.POST['team_name']
            team = Team(name=team_name, leader_id=request.user.id)
            if request.POST.get('team_desc'):
                team.desc = request.POST['team_desc']
            team.save()
            team.members.add(request.user)
            messages.success(request, "New team `{0}` has created successfully!".format(team))
            # After creating team, redirect user to task_manager index page with success message
            return redirect('taskmanager:index')
        else:
            messages.error(request, "Missing required fields!")
            return redirect(request.path)
    else:
        return render(request, 'taskmanager/team_create.html', {'user' : request.user})

@login_required
@require_http_methods(["GET"])
def team_detail(request, team_id):
    """
    Any member of team is able to see team details
    Only team leader is able to add or remove members.
    """
    team = get_object_or_404(Team, id=team_id)
    tasks = team.task_set.exclude(status='COMP')
    if request.user in team.members.all():
        return render(
            request,
            'taskmanager/team_detail.html',
            {'user' : request.user, 'team' : team, 'tasks' : tasks}
        )
    else:
        raise PermissionDenied

@login_required
@require_http_methods(["GET"])
def team_add_member(request, team_id):
    """
    Only leader of team is allowed to add members to team using username.
    """
    team = get_object_or_404(Team, id=team_id)
    if request.user == team.leader:
        try:
            user = UserModel.objects.get(username=request.GET['username'])
            if user not in team.members.all():
                team.members.add(user)
                messages.success(request, "The user `{0}` has added to your team successfully!".format(user))
            else:
                messages.error(request, "The user `{0}` is already in team".format(user))
        except:
            messages.error(request, "User with username `{0}` is not found".format(request.GET['username']))
        return redirect(team)
    else:
        raise PermissionDenied

@login_required
@require_http_methods(["GET"])
def team_remove_member(request, team_id):
    """
    Only leader of team is allowed to remove members of team using username.
    """
    team = get_object_or_404(Team, id=team_id)
    if request.user == team.leader:
        try:
            user = team.members.get(username=request.GET.get('username'))
            if request.user == team.leader:
                if user != team.leader:
                    team.members.remove(user)
                    messages.success(request, "The user `{0}` has been removed from team".format(user))
                elif user == team.leader:
                    messages.error(request, "Leader can not be removed from team!")
        except:
            messages.error(request, "User with username `{0}` is not found in your team!".format(request.GET.get('username')))
        return redirect(team)
    else:
        raise PermissionDenied

@login_required
@require_http_methods(["GET"])
def team_delete(request, team_id):
    """
    Only team leader is allowed to the delete team.
    Team can only be deleted if it's members does not contain any other user except leader.
    """
    team = get_object_or_404(Team, id=team_id)
    if request.user == team.leader and team.members.count() == 1:
        team.delete()
        messages.success(request, "The team is deleted successfully!")
        # Team is deleted, redirect user to index page
        return redirect('taskmanager:index')
    else:
        raise PermissionDenied

performance/templates/taskmanager/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
  <head lang="en">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'taskmanager/w3.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
<!--    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- Sidebar -->
  <div class="w3-sidebar w3-bar-block w3-border-right w3-animate-left" style="display:none" id="mySidebar">
    <button onclick="w3_close()" class="w3-bar-item w3-large">Close &times;</button>
    {% if user.is_authenticated %}
    {% load crispy_forms_tags %}
      <strong class="w3-bar-item"><i>{{ user.username }}</i></strong>
      <a href="{% url 'taskmanager:index' %}" class="w3-bar-item w3-button">Departments</a>
      <a href="{% url 'taskmanager:task_my_tasks' %}" class="w3-bar-item w3-button">My Tasks</a>
      <a href="{% url 'taskmanager:task_completed_tasks' %}" class="w3-bar-item w3-button">Completed Tasks</a>
      <a href="{% url 'taskmanager:task_create' %}" class="w3-bar-item w3-button">Add a Task</a>
      <a href="{% url 'taskmanager:team_create' %}" class="w3-bar-item w3-button">Create a Team</a>
      <form method="get" action="{% url 'taskmanager:task_search' %}" class="w3-margin-top w3-margin-bottom">
        <input type="text" name="q" class="w3-input w3-border" placeholder="Search task" required>
        <input type="submit" value="Search" class="w3-button w3-grey w3-margin">
      </form>
      <a href="{% url 'taskmanager:logout' %}" class="w3-bar-item w3-button">LogOut</a>
    {% else %}
      <a href="{% url 'taskmanager:signup' %}" class="w3-bar-item w3-button">Sign Up</a>
      <a href="{% url 'taskmanager:login' %}" class="w3-bar-item w3-button">Log In</a>
    {% endif %}
  </div>

  <!-- Page Content -->
  <div class="w3-teal">
    <button class="w3-button w3-teal w3-xlarge" onclick="w3_open()">+</button>
    <div class="w3-container">
      <h1 style="text-shadow:1px 1px 0 #444; text-align:center;">Task Manager</h1>
    </div>
  </div>

  <div class="w3-container">
    {% if messages %}
      {% for message in messages %}
        <div class="w3-panel w3-round-xlarge {% if message.tags == 'success' %}w3-pale-green{% else %}w3-pale-red{% endif %}" style="padding:10px">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
  </div>

  <script>
  function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
  }
  function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
  }
  </script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  </body>
</html>

performance/templates/taskmanager/index.html
{% extends "_layout.html" %}

{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h2 class="w3-card w3-padding-16 w3-light-grey">Your department:</h2><br />
    <ul class="w3-ul w3-hoverable w3-card-4">
        {% for team in teams %}
          <li class="w3-bar">
            <a href={{ team.get_absolute_url }} class="w3-bar-item">{{ team.name }}</a>
          </li>
        {% empty %}
          <li class="w3-bar">You are not in any team</li>
        {% endfor %}
    </ul>
  {% else %}
    <h2>You are not loggedIn, please Login or signUp</h2>
  {% endif %}
{% endblock %}

performance/templates/taskmanager/login.html
{% extends "taskmanager/base.html" %}

{% block title %}
  Login | Task Manager
{% endblock %}

{% block content %}

<form method="post" action="" class="w3-container w3-card w3-margin-top">
{% csrf_token %}
<label for="username"><b>Username : </b></label>
<input type="text" id="username" name="username" placeholder="Enter your username" class="w3-input w3-margin" maxlength="254" required autofocus>
<label for="password"><b>Password : </b></label>
<input type="password" id="password" name="password" placeholder="Enter your password" class="w3-input w3-margin" required>
<input type="hidden" name="next" value="{{ next }}">

<input type="submit" value="login" class="w3-button w3-green w3-margin w3-wide">

</form>

{% endblock %}

performance/templates/taskmanager/task_create-edit.html
{% extends '_layout.html' %}
{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}

{% block content %}
<style>
    ul li:hover{ background:white;}
    /*ul li span:hover ul{ display: none;}
    ul li ul li:last-child:hover .itam-2{display: block;}*/

</style>
<div class="w3-container w3-card w3-margin-top">
    <form method="post" action="">
        {% csrf_token %}
        <ul style="list-style:none;">
            <li style="text-align:left; margin-right: 0px;">
                {% for field in form %}
                <div class="w3-margin">

                    {% for error in field.errors %}
                    <div class="w3-panel w3-pale-red w3-round-xlarge">
                        {{ error }}
                    </div>
                    {% endfor %}

                    <b>{{ field.label_tag }}</b>
                    {{ field }}
                    {% if field.help_text %}
                    <span class="w3-small">
                {{ field.help_text }}
              </span>
                    {% endif %}
                </div>
                {% endfor %}
<!--No addition of other activities-->
            </li>
        </ul>

        <input type="submit" value="{% if creation %}Create Task{% else %}Save Changes{% endif %}"
               class="w3-button w3-green w3-margin w3-wide w3-right">
        {% comment %} <a href="{%url 'view_push'%}" class="w3-button w3-green w3-margin w3-wide w3-left">Send a push notification</a> {% endcomment %}


    </form>

<!--    <button id="myBtn">&#43;</button>-->
<!--    <button onclick="displaySub()">&#45;</button>-->
    {% if not creation %}
    <a href="{% url 'taskmanager:task_delete' task.id %}">
        <button class="w3-button w3-red w3-margin w3-left">Delete Task</button>
    </a>
    {% endif %}

</div>
<script>
document.getElementById("myBtn").addEventListener("click", displayAdd);

function displayAdd() {
    document.getElementById("myUL").style.display = "block";
}
function displaySub(){
    document.getElementById("myUL").style.display = "none";
}

</script>

{% endblock %}


performance/templates/taskmanager/task_detail.html
{% extends '_layout.html' %}

{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}

{% block content %}
  <div class="w3-cell-row">
    <div class="w3-card w3-container w3-cell w3-cell-middle w3-mobile">
      <h2 class="w3-padding-16">{{ task.title }}</h2>

      {% if task.desc %}
        {{ task.desc|safe|urlize|linebreaks }}
      {% endif %}

      {# user having task assigned to and task creator can mark task as In-rogress or Completed #}
      {% if user in task.assigned_to.all or user == task.creator %}
        <div class="w3-bar w3-center">
          {% if task.status == 'PLAN' and user in task.assigned_to.all %}
            <a href="{% url 'taskmanager:task_accept' task.id %}">
              <button class="w3-button w3-blue">Accept the Task</button>
            </a>
          {% endif %}
          {% if task.status == 'PROG' %}
            <a href="{% url 'taskmanager:task_mark_completed' task.id %}">
              <button class="w3-button w3-blue w3-margin-bottom">Mark Completed</button>
            </a>
          {% endif %}

          {# Only task creator can edit the task #}
          {% if user == task.creator and task.status == 'PLAN' %}
            <a href="{% url 'taskmanager:task_edit' task.id %}">
              <button class="w3-button w3-green w3-margin-bottom w3-margin-top">Edit Task</button>
            </a>
          {% endif %}
        </div>
      {% endif %}
    </div>

  <div class="w3-card w3-container w3-cell w3-cell-middle w3-mobile">
    <p class="w3-border-bottom"><strong>Created By : </strong><i>{{ task.creator }}</i></p>
      <p class="w3-border-bottom">
        <strong>Status : </strong>
        <span class="w3-tag w3-blue w3-round-large">{{ task.get_status_display }}</span>
      </p>
      <p><strong>Assigned To : </strong>
        <ul class="w3-ul w3-center">
        {% for u in task.assigned_to.all %}
          <li><i>{{ u }}</i></li>
        {% endfor %}
        </ul>
      </p>
      {% if task.team %}
        <p class="w3-border-bottom"><strong>Assigned to team : </strong>
          <a href="{{ task.team.get_absolute_url }}">{{ task.team }}</a>
        </p>
      {% endif %}
      <p class="w3-border-bottom"><strong>Planned on : </strong>{{ task.planned_date }}</p>
      <p class="w3-border-bottom"><strong>Due Date : </strong>{{ task.due_date }}</p>
      {% if task.status == 'PROG' or task.status == 'COMP' %}
        <p class="w3-border-bottom"><strong>Accepted on : </strong>{{ task.accepted_date }}</p>
        <p class="w3-border-bottom"><strong>Accepted By : </strong>{{ task.accepted_by }}</p>
      {% endif %}
      {% if task.status == 'COMP' %}
        <p class="w3-border-bottom"><strong>Completed on : </strong>{{ task.completed_date }}</p>
      {% endif %}
    </div>
  </div>

  <!-- Comment form -->
  <div class="w3-container">
    <h5>Add comment:</h5>
    <form action="{% url 'taskmanager:task_comment' task.id %}" method="post">
      {% csrf_token %}
      <textarea class="w3-input w3-border" name="comment_body" rows="3" placeholder="Write your comment here" required></textarea>
      <input class="w3-button w3-wide w3-green w3-margin-top" type="submit" value="Add Comment">
    </form>
  </div>

  <!-- Comment's section -->
  <div class="w3-card w3-margin-top w3-container">
    <h4><b>Comments on this task:</b></h4>
    <hr>
    {% for comment in task.comment_set.all %}
      <p>
        <b>
          <i>{{ comment.author }}</i>,
          {{ comment.time }}
        </b>
      </p>
      {{ comment.body|safe|urlize|linebreaks }}
      <hr>
    {% empty %}
    No Comments (yet).
    <hr>
    {% endfor %}
  </div>

{% endblock %}

performance/templates/taskmanager/task_search_results.html
{% extends '_layout.html' %}

{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}

{% block content %}
  <h2>{{ found_tasks.count }} search results for : "{{ query_string }}"</h2>
  {% if found_tasks %}
    <table class="w3-table w3-striped w3-bordered w3-card-4 w3-hoverable">
      <tr class="w3-green">
        <th>Title</th>
        <th>Team</th>
        <th>Created By</th>
        <th>Assigned to</th>
        <th>Due Date</th>
        <th>Status</th>
        <th>Completed Date</th>
      </tr>
      {% for task in found_tasks %}
        <tr>
          <td><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></td>
          <td>
            {% if task.team %}
              <a href={{ task.team.get_absolute_url }}>{{ task.team }}</a>
            {% else %}
              ----
            {% endif %}
          </td>
          <td>{{ task.creator }}</td>
          <td>
            <ul class="w3-ul" style="width:36%">
              {% for u in task.assigned_to.all %}
                <li><i>{{ u }}</i></li>
              {% endfor %}
            </ul>
          </td>
          <td>{{ task.due_date }}</td>
          <td>{{ task.get_status_display }}</td>
          <td>{{ task.completed_date }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}

{% endblock %}

performance/templates/taskmanager/team_detail.html
{% extends "_layout.html" %}

{% block navheader %}
{% include 'includes/navheader_employee_app.html' %}
{% endblock %}

{% block content %}
<div class="w3-card-4 w3-padding-16 w3-light-grey w3-margin-bottom w3-margin-top">
  <div class="w3-margin-left">
    <h2 class="">{{ team.name }}</h2>
    {% if team.desc %}
      <p>{{ team.desc|safe|linebreaks }}</p>
    {% endif %}
  </div>
  {% if team.members.count == 1 %}
    <div class="w3-margin">
      Your team is empty.
      <a href="{% url 'taskmanager:team_delete' team.id %}">
        <button class="w3-button w3-red w3-margin">Delete Team</button>
      </a>
    </div>
  {% endif %}
</div>

<b>
  Tasks assigned to team :
</b>
<p>{{ tasks.count }} task(s) are assigned to team!</p>
{% if tasks %}
  <table class="w3-table w3-striped w3-bordered w3-card-4 w3-hoverable">
    <tr class="w3-green">
      <th>Title</th>
      <th>Assigned to</th>
      <th>Due Date</th>
      <th>Status</th>
    </tr>
    {% for task in tasks %}
      <tr>
        <td><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></td>
        <td>
          <ul class="w3-ul" style="width:36%">
            {% for u in task.assigned_to.all %}
              <li><i>{{ u }}</i></li>
            {% endfor %}
          </ul>
        </td>
        <td class="{% if task.is_overdated %}w3-red{% endif %}">{{ task.due_date }}</td>
        <td>{{ task.get_status_display }}</td>
      </tr>
    {% endfor %}
  </table>
{% endif %}

<div class="w3-margin-top">
  <b><p>Members: </p></b>
  <ul class="w3-ul w3-card-2">
    {% for member in team.members.all %}
      <li class="w3-bar">
        <div class="w3-bar-item">
          <span class="w3-large">{{ member }}</span>
          {% if member == team.leader %}
            <span class="w3-badge w3-green">leader</span>
          {% endif %}
        </div>
        {% if user == team.leader and member != team.leader %}
          <a href="{% url 'taskmanager:team_remove_member' team.id %}?username={{ member.username }}">
            <span class="w3-bar-item w3-button w3-large w3-right" style="color:red">Remove</span>
          </a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>

{# Members addition form #}
{% if user == team.leader %}
  <div class="w3-card w3-center w3-margin-top w3-row-padding">
  <form method="get" action="{% url 'taskmanager:team_add_member' team.id %}" class="w3-container">
    <p class="w3-margin-top">Add a user with username:</p>
    <input class="w3-input w3-section" type="text" name="username" placeholder="Enter username of member to add" autocomplete="off" spellcheck="false" required>
    <input type="submit" value="Add user" class="w3-button w3-wide w3-green w3-section">
  </form>
  </div>
{% endif %}

{% endblock %}