performance/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('create-user/',views.register_user_view,name='register'),
    path('user/change-password/',views.changepassword,name='changepassword'),
    path('user/profile/view/',views.user_profile_view,name='userprofile'),
   

    #Users Views
    path('users/all',views.users_list,name='users'),
    path('users/<int:id>/block',views.users_block,name='userblock'),
    path('users/<int:id>/unblock',views.users_unblock,name='userunblock'),
    path('users/blocked/all',views.users_blocked_list,name='erasedusers'),


]

performance/dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    # Emergency
    path('emergency/create/',views.dashboard_emergency_create,name='emergencycreate'),
    path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # Family
    path('family/create/',views.dashboard_family_create,name='familycreate'),
    path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    #Bank
    path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    # BIRTHDAY ROUTE
    path('birthdays/all/',views.birthday_this_month,name='birthdays'),



]

performance/setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from taskmanager.views.tasks import send_push,view_push
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),  # change url in production --> Actservsuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('task-master/', include('taskmanager.urls')),
    # path('',view_push, name='view_push'),
    path('send_push', send_push, name='send_push'),
    path('reports/', include('reports.urls', namespace='reports')),
    path('webpush/', include('webpush.urls')),
    path('select2/', include('django_select2.urls')),
]

urlpatterns += [
    path('pams_system/', include('pams_system.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
admin.site.site_header = 'Actserv ADMINISTRATION'

performance/taskmanager/urls.py
"""Task Manager URL Configuration

"""
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from taskmanager import views

# from . import views

app_name = 'taskmanager'

urlpatterns = [
    path('', views.index, name='index'),
    path('teams/<int:team_id>/', views.team_detail, name='team_detail'),
    path('teams/create/', views.team_create, name='team_create'),
    path('teams/<int:team_id>/remove-member/', views.team_remove_member, name='team_remove_member'),
    path('teams/<int:team_id>/add-member/', views.team_add_member, name='team_add_member'),
    path('teams/<int:team_id>/delete/', views.team_delete, name='team_delete'),
    path('my-tasks/', views.tasks, name='task_my_tasks'),
    path('my-completed-tasks/', views.completed_tasks, name='task_completed_tasks'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/edit/', views.task_edit, name='task_edit'),
    path('tasks/<int:task_id>/comment/', views.task_comment, name='task_comment'),
    path('tasks/<int:task_id>/accept/', views.task_accept, name='task_accept'),
    path('tasks/<int:task_id>/mark-completed/', views.task_mark_completed, name='task_mark_completed'),
    path('tasks/<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('tasks/search/', views.task_search, name='task_search'),
    # path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    # path('logout/', views.logout, name='logout'),
]

# urlpatterns += [
# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

performance/templates/includes/navheader_default.html
 {% load static %}
 <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href=""></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">

                        <li>
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                <i class=""></i>
								<p class="hidden-lg hidden-md"></p>
                            </a>
                        </li>

                        {% if request.user.authenticated %}
                        <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-bell"><span style="font-size: 14px !important; padding-left: 2px;">{{ leaves.count }}</span></i>
                                    <b class="caret hidden-lg hidden-md"></b>
									<p class="hidden-lg hidden-md">
										<b class="caret"></b>
									</p>
                              </a>
                              {% if leaves %}
                              <ul class="dropdown-menu">
                                {% for leave in leaves %}
                                <li><a href="{% url 'dashboard:userleaveview' leave.id %}">{{ leave.pretty_leave }}</a></li>
                                {% endfor %}
                              </ul>
                              {% endif %}

                        </li>
                        {% endif %}

                        <li>
                           <a href="{% url 'dashboard:birthdays' %}">
                                <i class="pe-7s-gift"></i><span style="font-size: 13px;"> ({{ employees_birthday.count }})</span>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
              <!--           <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
										Dropdown
										<b class="caret"></b>
									</p>

                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="">Actio ghn</a></li>
                                <li><a href="">Another action</a></li>
                                <li><a href="">Something</a></li>
                                <li><a href="">Another action</a></li>
                                <li><a href="">Something</a></li>
                                <li class="divider"></li>
                                <li><a href="">Separated link</a></li>
                              </ul>
                        </li> -->
                         <li class="dropdown">
                              <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        <i class="fa fa-user"></i> {{ request.user}}
                                        <b class="caret"></b>
                                    </p>

                              </a>
                              <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout'  %}">Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'accounts:login'  %}">Login</a></li>
                                {% endif %}
                                <li><a href="{% url 'accounts:userprofile' %}">Profile</a></li>
                                <li><a href="{% url 'accounts:changepassword' %}">Change Password</a></li>
                                <!-- <li class="divider"></li>
                                <li><a href="">Settings</a></li> -->
                              </ul>
                        </li>
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>

performance/templates/includes/navheader_employee_app.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed shadow">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- <a class="navbar-brand" href="">Dashboard </a> -->
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">

                <li>
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <i class=""></i>
                        <p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>


                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            Leave
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_superuser %}
                        <li><a href="{% url 'dashboard:leaveslist' %}">Pending Leaves</a></li>
                        <li><a href="{% url 'dashboard:approvedleaveslist' %}">Approved Leaves</a></li>
                        <li><a href="{% url 'dashboard:canceleaveslist' %}">Cancelled Leaves</a></li>
                        <li><a href="{% url 'dashboard:leavesrejected' %}">Rejected Leaves</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'dashboard:createleave' %}">Apply for Leave</a></li>
                        {% else %}
                        <li><a href="{% url 'dashboard:createleave' %}">Apply for Leave</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'dashboard:staffleavetable' %}">All Leaves</a></li>
                        {% endif %}
                    </ul>
                </li>


                {% if request.user.is_superuser and request.user.is_staff %}
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            Employee
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'dashboard:employeecreate' %}">Add Employee</a></li>
                        <li><a href="{% url 'dashboard:employees' %}">All Employees</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'dashboard:emergencycreate' %}">+ Emergency</a></li>
                        <li><a href="{% url 'dashboard:familycreate' %}">+ Family</a></li>
                        <li><a href="{% url 'dashboard:bankaccountcreate' %}">+ Bank Account</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'accounts:erasedusers' %}">Deleted Employees</a></li>
                    </ul>
                </li>
                {% endif %}

                {% if request.user.is_superuser and request.user.is_staff %}
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            Users
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'accounts:register' %}">Create Users</a></li>
                        <li><a href="{% url 'accounts:users' %}">All Users</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if request.user.is_superuser and request.user.is_staff %}
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            Performance
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'mapTypeIndex' %}">+ Maptypes</a></li>
                        <li class="divider">Levels</li>
                        <li><a href="#">+ Levels</a></li>
                        <li class="divider"></li>
                        <li><a href="#">+ KPIs</a></li>
                    </ul>
                </li>
                {% endif %}

                {% if request.user.is_superuser and request.user.is_staff %}
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            Task Manager
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'taskmanager:index' %}">Departments</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'taskmanager:task_my_tasks' %}">My Tasks</a></li>
                        <li><a href="{% url 'taskmanager:task_completed_tasks' %}">Completed Tasks</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'taskmanager:task_create' %}">+ Tasks</a></li>
                        <li><a href="{% url 'taskmanager:team_create' %}">+ Teams</a></li>
                        <li class="divider"></li>
                    </ul>
                </li>
                {% endif %}

                {% if request.user.is_superuser and request.user.is_staff %}
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            Reports
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'reports:index' %}">My Report</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'reports:index' %}">Admin Reports</a></li>
                    </ul>
                </li>
                {% endif %}

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'dashboard:birthdays' %}" title="upcoming birthday">
                        <i class="pe-7s-gift"></i>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="" class="dropdown-toggle refresh-page" data-toggle="dropdown" title="refresh current page">
                        <i class="pe-7s-refresh-2"></i>
                        <b class="hidden-lg hidden-md"></b>
                        <p class="hidden-lg hidden-md">
                            refresh

                        </p>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <p>
                            <i class="fa fa-user"></i> {{ request.user}}
                            <b class="caret"></b>
                        </p>

                    </a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout'  %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login'  %}">Login</a></li>
                        {% endif %}
                        <li><a href="{% url 'accounts:userprofile' %}">Profile</a></li>
                        <li><a href="{% url 'accounts:changepassword' %}">Change Password</a></li>
                        <!-- <li class="divider"></li>
                        <li><a href="">Settings</a></li> -->
                    </ul>
                </li>

                <li class="separator hidden-lg"></li>
            </ul>
        </div>
    </div>
</nav>