performance/dashboard/urls.py
from django.urls import path
from .import views


app_name = 'dashboard'

urlpatterns = [
    path('welcome/',views.dashboard,name='dashboard'),

    # Employee
    path('employees/all/',views.dashboard_employees,name='employees'),
    path('employee/create/',views.dashboard_employees_create,name='employeecreate'),
    path('employee/profile/<int:id>/',views.dashboard_employee_info,name='employeeinfo'),
    path('employee/profile/edit/<int:id>/',views.employee_edit_data,name='edit'),

    # Emergency
    path('emergency/create/',views.dashboard_emergency_create,name='emergencycreate'),
    path('emergency/update/<int:id>',views.dashboard_emergency_update,name='emergencyupdate'),

    # Family
    path('family/create/',views.dashboard_family_create,name='familycreate'),
    path('family/edit/<int:id>',views.dashboard_family_edit,name='familyedit'),
    
    #Bank
    path('bank/create/',views.dashboard_bank_create,name='bankaccountcreate'),

    #---work-on-edit-view------#
    path('bank/edit/<int:id>/',views.employee_bank_account_update,name='accountedit'),
    path('leave/apply/',views.leave_creation,name='createleave'),
    path('leaves/pending/all/',views.leaves_list,name='leaveslist'),
    path('leaves/approved/all/',views.leaves_approved_list,name='approvedleaveslist'),
    path('leaves/cancel/all/',views.cancel_leaves_list,name='canceleaveslist'),
    path('leaves/all/view/<int:id>/',views.leaves_view,name='userleaveview'),
    path('leaves/view/table/',views.view_my_leave_table,name='staffleavetable'),
    path('leave/approve/<int:id>/',views.approve_leave,name='userleaveapprove'),
    path('leave/unapprove/<int:id>/',views.unapprove_leave,name='userleaveunapprove'),
    path('leave/cancel/<int:id>/',views.cancel_leave,name='userleavecancel'),
    path('leave/uncancel/<int:id>/',views.uncancel_leave,name='userleaveuncancel'),
    path('leaves/rejected/all/',views.leave_rejected_list,name='leavesrejected'),
    path('leave/reject/<int:id>/',views.reject_leave,name='reject'),
    path('leave/unreject/<int:id>/',views.unreject_leave,name='unreject'),
    # BIRTHDAY ROUTE
    path('birthdays/all/',views.birthday_this_month,name='birthdays'),



]

performance/setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from taskmanager.views.tasks import send_push,view_push
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),  # change url in production --> Actservsuits.com/_&_wysiwyg-suits_empty-link_url
    path('', views.index_view, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('task-master/', include('taskmanager.urls')),
    # path('',view_push, name='view_push'),
    path('send_push', send_push, name='send_push'),
    path('reports/', include('reports.urls', namespace='reports')),
    path('webpush/', include('webpush.urls')),
    path('select2/', include('django_select2.urls')),
]

urlpatterns += [
    path('pams_system/', include('pams_system.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
admin.site.site_header = 'Actserv ADMINISTRATION'

performance/dashboard/models.py
from django.db import models

# Create your models here.

performance/dashboard/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models import Q
import datetime
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from employee.forms import EmployeeCreateForm,EmergencyCreateForm,FamilyCreateForm,BankAccountCreation
from leave.models import Leave
from employee.models import *
from leave.forms import LeaveCreationForm
# from leave.forms import CommentForm

def dashboard(request):
	
	'''
	Summary of all apps - display here with charts etc.
	eg.lEAVE - PENDING|APPROVED|RECENT|REJECTED - TOTAL THIS MONTH or NEXT MONTH
	EMPLOYEE - TOTAL | GENDER 
	CHART - AVERAGE EMPLOYEE AGES
	'''
	dataset = dict()
	user = request.user

	if not request.user.is_authenticated:
		return redirect('accounts:login')

	employees = Employee.objects.all()
	leaves = Leave.objects.all_pending_leaves()
	employees_birthday = Employee.objects.birthdays_current_month()
	staff_leaves = Leave.objects.filter(user = user)

	
	dataset['employees'] = employees
	dataset['leaves'] = leaves
	dataset['employees_birthday'] = employees_birthday
	dataset['staff_leaves'] = staff_leaves
	dataset['title'] = 'summary'
	

	return render(request,'dashboard/dashboard_index.html',dataset)




def dashboard_employees(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')

	dataset = dict()
	departments = Department.objects.all()
	employees = Employee.objects.all()

	#pagination
	query = request.GET.get('search')
	if query:
		employees = employees.filter(
			Q(firstname__icontains = query) |
			Q(lastname__icontains = query)
		)



	paginator = Paginator(employees, 10) #show 10 employee lists per page

	page = request.GET.get('page')
	employees_paginated = paginator.get_page(page)


	dataset['employee_list'] = employees_paginated
	dataset['departments'] = departments
	dataset['all_employees'] = Employee.objects.all_employees()

	blocked_employees = Employee.objects.all_blocked_employees()

	dataset['blocked_employees'] = blocked_employees
	dataset['title'] = 'Employees list view'
	return render(request,'dashboard/employee_app.html',dataset)




def dashboard_employees_create(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')

	if request.method == 'POST':
		form = EmployeeCreateForm(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit = False)
			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user

			instance.title = request.POST.get('title')
			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			instance.sex = request.POST.get('sex')
			instance.bio = request.POST.get('bio')
			instance.birthday = request.POST.get('birthday')

			religion_id = request.POST.get('religion')
			religion = Religion.objects.get(id = religion_id)
			instance.religion = religion

			nationality_id = request.POST.get('nationality')
			nationality = Nationality.objects.get(id = nationality_id)
			instance.nationality = nationality

			department_id = request.POST.get('department')
			department = Department.objects.get(id = department_id)
			instance.department = department


			instance.hometown = request.POST.get('hometown')
			instance.region = request.POST.get('region')
			instance.residence = request.POST.get('residence')
			instance.address = request.POST.get('address')
			instance.education = request.POST.get('education')
			instance.lastwork = request.POST.get('lastwork')
			instance.position = request.POST.get('position')
			instance.ssnitnumber = request.POST.get('ssnitnumber')
			instance.tinnumber = request.POST.get('tinnumber')

			role = request.POST.get('role')
			role_instance = Role.objects.get(id = role)
			instance.role = role_instance

			instance.startdate = request.POST.get('startdate')
			instance.employeetype = request.POST.get('employeetype')
			instance.employeeid = request.POST.get('employeeid')
			instance.dateissued = request.POST.get('dateissued')

			# now = datetime.datetime.now()
			# instance.created = now
			# instance.updated = now

			instance.save()

			# employee_email = instance.user.email
			# email_subject = 'Humanly Access Credentials'
			# email_message = 'You have been added to Actservgroup Staff List,username and password'
			# from_email = settings.EMAIL_HOST_USER
			# to_email = [employee_email]
			'''
			Work on it - user@gmail.com & user@Actservgroup.com -> send Template
			'''
			# send_mail(
			# 	email_subject,
			# 	email_message,
			# 	from_email,
			# 	to_email,
			# 	fail_silently=True
			# 	)

			#Send email - username & password to employee, how to get users decrypted password ?

			return  redirect('dashboard:employees')
		else:
			messages.error(request,'Trying to create dublicate employees with a single user account ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('dashboard:employeecreate')


	dataset = dict()
	form = EmployeeCreateForm()
	dataset['form'] = form
	dataset['title'] = 'register employee'
	return render(request,'dashboard/employee_create.html',dataset)





def employee_edit_data(request,id):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')
	employee = get_object_or_404(Employee, id = id)
	if request.method == 'POST':
		form = EmployeeCreateForm(request.POST or None,request.FILES or None,instance = employee)
		if form.is_valid():
			instance = form.save(commit = False)

			user = request.POST.get('user')
			assigned_user = User.objects.get(id = user)

			instance.user = assigned_user

			instance.title = request.POST.get('title')
			instance.image = request.FILES.get('image')
			instance.firstname = request.POST.get('firstname')
			instance.lastname = request.POST.get('lastname')
			instance.othername = request.POST.get('othername')
			instance.sex = request.POST.get('sex')
			instance.bio = request.POST.get('bio')
			instance.birthday = request.POST.get('birthday')

			religion_id = request.POST.get('religion')
			religion = Religion.objects.get(id = religion_id)
			instance.religion = religion

			nationality_id = request.POST.get('nationality')
			nationality = Nationality.objects.get(id = nationality_id)
			instance.nationality = nationality

			department_id = request.POST.get('department')
			department = Department.objects.get(id = department_id)
			instance.department = department


			instance.hometown = request.POST.get('hometown')
			instance.region = request.POST.get('region')
			instance.residence = request.POST.get('residence')
			instance.address = request.POST.get('address')
			instance.education = request.POST.get('education')
			instance.lastwork = request.POST.get('lastwork')
			instance.position = request.POST.get('position')
			instance.ssnitnumber = request.POST.get('ssnitnumber')
			instance.tinnumber = request.POST.get('tinnumber')

			role = request.POST.get('role')
			role_instance = Role.objects.get(id = role)
			instance.role = role_instance

			instance.startdate = request.POST.get('startdate')
			instance.employeetype = request.POST.get('employeetype')
			instance.employeeid = request.POST.get('employeeid')
			instance.dateissued = request.POST.get('dateissued')

			# now = datetime.datetime.now()
			# instance.created = now
			# instance.updated = now

			instance.save()
			messages.success(request,'Account Updated Successfully !!!',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect('dashboard:employees')

		else:

			messages.error(request,'Error Updating account',extra_tags = 'alert alert-warning alert-dismissible show')
			return HttpResponse("Form data not valid")

	dataset = dict()
	form = EmployeeCreateForm(request.POST or None,request.FILES or None,instance = employee)
	dataset['form'] = form
	dataset['title'] = 'edit - {0}'.format(employee.get_full_name)
	return render(request,'dashboard/employee_create.html',dataset)






def dashboard_employee_info(request,id):
	if not request.user.is_authenticated:
		return redirect('/')
	
	employee = get_object_or_404(Employee, id = id)
	employee_emergency_instance = Emergency.objects.filter(employee = employee).first()
	employee_family_instance = Relationship.objects.filter(employee = employee).first()
	bank_instance = Bank.objects.filter(employee = employee).first()
	
	dataset = dict()
	dataset['employee'] = employee
	dataset['emergency'] = employee_emergency_instance
	dataset['family'] = employee_family_instance
	dataset['bank'] = bank_instance
	dataset['title'] = 'profile - {0}'.format(employee.get_full_name)
	return render(request,'dashboard/employee_detail.html',dataset)




# ------------------------- EMERGENCY --------------------------------


def dashboard_emergency_create(request):
	if not (request.user.is_authenticated and request.user.is_superuser and request.user.is_staff):
		return redirect('/')
	if request.method == 'POST':
		form = EmergencyCreateForm(data = request.POST)
		if form.is_valid():
			instance = form.save(commit = False)
			employee_id = request.POST.get('employee')

			employee_object = Employee.objects.get(id = employee_id)
			emp_name = employee_object.get_full_name
			
			instance.employee = employee_object
			instance.fullname = request.POST.get('fullname')
			instance.tel = request.POST.get('tel')
			instance.location = request.POST.get('location')
			instance.relationship = request.POST.get('relationship')

			# now = datetime.datetime.now()
			# instance.created = now

performance/templates/dashboard/employee_app.html
{% extends '_layout.html' %}
{% block title %} {{ title }} {% endblock %}


 {% block navheader %}
 	{% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



   {% block stylesheet %}
	   	.fa-eye,.fa-pencil{
	   	    margin-right: 5px;
	   }

	   .table-shadow{
	   	background: white;
    	padding: 2%;
    	-webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(	0,0,0,0.2);
    	box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
	}
	

	h4{
	margin:2px 0 5px 0 !important;
	}



	.table-description{
		<!-- STYLE WITH GOOGLE FONT -->
	}

	.download-print-action{
		padding-bottom: 12px;
	}


    #override-start{
	    background:none !important;
	    top: 35% !important;
	    right:13px;
	    color:#000;
	    font-size: 24px;

	}

	.alert-warning{
	    background:#fd7b7b;
	}

	.alert-success {
	    background-color: #82b72a;
	}

	.alert-success,.alert-warning{
	    font-size:16px;
	}

	.sec-box{
	 <!-- width:200px; --><!-- enabled -> removes box responsiveness : avoid this -->
     height:80px;
     max-width:100%;
     line-height:80px;
     text-align:center;
     position:relative;
     
     font-size:1.9rem;

    -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
    transition: all 400ms ease-in;

    font-variant: petite-caps;
}


.sec-box a{
 color:#fff;
 text-decoration:none;
	
}


 .employee-box{
 	background:#3f9a26;
}


 .leave-box{
 	background:#fff;

}

.leave-box a{
	color:#3ea7c7 !important;
}


 .birthday-box{
 	background:#8664ad;
}

.deleted-box{
	background:#d42828;
}

.company-box{
	background:#868686;
}

.margin-bottom{
	margin-bottom:1.4rem;
}

.count-object {
    position: absolute;
    top: 31%;
    right: 12px;
    font-size: 25px;
    font-weight: 100;
    font-variant: petite-caps;
    color: #f5f5f5;
    text-shadow:1px 1px rgba(8, 8, 8, 0.23);
}

.deprt{
	color:#4195bd !important;
}


#stylebutton{
	background: #60a0b3 !important;
    color: #fff !important;
    font-variant: petite-caps !important;
    font-size: 14px !important;
}

.input-group-btn + input:focus{
	outline:#60a0b3;
}





{% endblock %}


        <!--CONTENTS-->
 {% block content %}
        <section class="content">
            <section class="container-fluid">
            	<section class="row">
	            		<section class="col col-lg-12">
	            			<a href="{{request.META.HTTP_REFERER|escape}}" style="color:#c1c1c1;">back</a>
	            		</section>
            	</section>
            	   <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>
                    <!-- <div class="container"> -->
                    <section class="row margin-bottom">
                    	<div class="container-fluid">
                    	<section class="col-lg-4 col-md-4 col-sm-12">
	            			<div class="employee-box sec-box">
	            				<a href="">
	            				<span>Employees</span>
	            				</a>
	            				<span class="count-object">{{ all_employees.count }}</span> 
	            			</div>
            			</section>
	            		<section class="col-lg-4 col-md-4 col-sm-12">
	            			<div class="leave-box sec-box">
	            				<a href="">
	            				<span>Departments</span>
	            				</a>
	            				<span class="count-object deprt">{{ departments.count }}</span>
	            			</div>
	            		</section>
	            		<section class="col-lg-4 col-md-4 col-sm-12">
	            			<div class="birthday-box sec-box">
	            				<a href="">
	            				<span>Blocked Users</span>
	            				</a>
	            				<span class="count-object">{{ blocked_employees.count }}</span> 
	            			</div>
	            		</section>
	            		<!-- <section class="col col-lg-4">
	            			<div class="deleted-box sec-box">
	            				<a href="">
	            				<span>Deleted</span>
	            				</a>
	            			</div>
	            		</section> -->
	            		</div>
                    </section><!-- /row -->

                    <!-- </div> -->
                    <!-- Search form -->
					<div class="row" style="margin-bottom: 2.2rem;margin-top: 3rem;">
					 <div class="">
					  <div class="col-lg-12">

					  	<form action="" method="GET">
						    <div class="input-group">
						      <span class="input-group-btn">
						        <button class="btn btn-default" id = "stylebutton" type="button">Search</button>
						      </span>
						      <input type="search" value="{{request.GET.search}}" name="search" class="form-control" placeholder="Search by firstname,lastname...">
						    </div><!-- /input-group -->
					    </form>

					  </div><!-- /.col-lg-6 -->
					  </div>
					</div><!-- /.row -->
					<!-- /search form -->

                	<!-- TABLE -->
                	<div class="table-responsive table-shadow">
                		<div class="text-center table-description">
                			<h4 class="title-h3" style="color: #60a0b3 !important;
    						text-shadow: 1px 0px rgba(0,0,0,0.11)">ALL EMPLOYEES TABLE</h4>
                		</div>
                		<div class="container-fluid">
                			<div class="row">
                			 	<div class="download-print-action">
                			  		Download Excel | Pdf | Print <!-- Work on pdf and excel and print -->
                			  		
                				</div>
                			</div>
                		</div>
                		<table class="table">
							  <thead>
							    <tr>
							      <th scope="col">#</th>
							      <th scope="col">Fullname</th>
							      <th scope="col">Role</th>
							      <th scope="col">Department</th>
							      <th scope="col">Status</th>
							      <th scope="col">Actions</th>
							    </tr>
							  </thead>
							  <tbody>
							  	{% for employee in employee_list %}
							    <tr>

							      {% if employee.employeeid %}
							      <th scope="row">{{ employee.employeeid }}</th>
							      {% else %}
							      <th scope="row">-</th>
							      {% endif %}

							      <td>{{ employee.get_full_name }}</td>
							      <td>{{ employee.role }}</td>
							      <td>{{ employee.department }}</td>

							      {% if employee.is_blocked %}
							      <td>Inactive</td>
							      {% else %}
							      <td>active</td>
							      {% endif %}

							      <td> 
							      	<a href="{% url 'dashboard:employeeinfo' employee.id %}">
							      	    view
							      	</a>
							      	
							        <a href="{% url 'dashboard:edit' employee.id %}">
							       	edit
							        </a>

							      </td>
							    </tr>
							    {% endfor %}

							  </tbody>

						</table>
						<!-- Pagination -->
							  <div class="pagination">
							    <span class="step-links">
							        {% if employee_list.has_previous %}
							            <a href="?page=1">&laquo; first</a>
							            <a href="?page={{ employee_list.previous_page_number }}">previous</a>
							        {% endif %}

							        <span class="current">
							            Page {{ employee_list.number }} of {{ employee_list.paginator.num_pages }}.
							        </span>

							        {% if employee_list.has_next %}
							            <a href="?page={{ employee_list.next_page_number }}">next</a>
							            <a href="?page={{ employee_list.paginator.num_pages }}">last &raquo;</a>
							        {% endif %}
							    </span>
							</div>
						<!-- /pagination -->


					</div>
                	<!-- /TABLE -->

            </section> <!-- /container --> 


        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}
/*create-user-button - handler*/

// $(document).ready(function(){

// var createuser = $('.create-user-model');
// createuser.on('click',function(){
// alert("who clicked me ?")

// });


// });

{% endblock %}
</script>

performance/templates/dashboard/leave_detail_view.html
{% extends '_layout.html' %}

{% block title %} {{ title }} {% endblock %}

{% load crispy_forms_tags %}

 {% block navheader %}
    {% include 'includes/navheader_employee_app.html' %}
 {% endblock %}



  {% block stylesheet %}
    .rounded-circle-image{
    border-radius: 50% !important;
    width:250px;
    height:250px;
  }

  .form-wrapper{
  background:#fff;
  -webkit-box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);
  box-shadow: 0 2px 2px 0 rgba(0,0,0,0.14), 0 3px 1px -2px rgba(0,0,0,0.12), 0 1px 5px 0 rgba(0,0,0,0.2);

  padding-top: 2rem;
  padding-bottom: 2rem;

}


.list-group {
  margin-top: 10px;
}

span{
  color: #6f6f6f;
  font-weight: lighter;
  font-size: 16px;
}


.list-group-item {
    position: relative;
    display: block;
    padding: 10px 15px;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid transparent;
    font-size:17px;
}

  #override-start{
    background:none !important;
    top: 35% !important;
    right:13px;
    color:#000;
    font-size: 24px;

    }

    .alert-warning{
        background:#fd7b7b;
    }

    .alert-success {
        background-color: #82b72a;
    }

    .alert-success,.alert-warning{
        font-size:16px;
    }

    .employee-name-title{
    color: #3873b1;
    font-weight: 600;
    font-variant: petite-caps;
    font-size: 3.1rem !important;
  }

  span,.list-group-item > div{
  font-variant: petite-caps;
}


.panel-default>.panel-heading {
    color: #fff !important;
    background-color: #2d88a9 !important;
}

.panel-title a:hover{
  color:#e6e4e4;
}

.panel-title a:active{
  color:#e6e4e4;
}

.panel-title a:focus{
  color:#e6e4e4;
}



  {% endblock %}


  

 {% block content %}
        <section class="content">
            <section class="container-fluid">
           
                <section class="form-wrapper">
                    <section class="row">
                        <section class="col col-lg-8 col-md-12  col-sm-12">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-12 col-md-12 col-sm-12 text-center space-margin">
                            <h3 class="title-h3">{{ employee.get_full_name }}</h3>
                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-4 text-center">
                          <img src="{{ employee.image.url}}"  class="img-fluid rounded-circle-image">
                        </section>
                        <section class="col-lg-8 col-md-12 col-sm-12">
                                    <div class="list-group" id="list-tab" role="tablist">
                                            <a class="list-group-item list-group-item-action" id="list-home-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Employee</span> <div>{{ employee.get_full_name }}</div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Start Date</span> <div> Start Date {{ leave.startdate }}</div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="" role="tab" aria-controls=""><span>End Date</span><div>{{ leave.enddate}}</div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Duration</span> <div>{{ leave.leave_days}}</div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Type</span> <div>{{ leave.leavetype}}</div>
                                            </a>
                                            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Reason</span> <div>{{ leave.reason}}</div>
                                            </a>
                                             <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="" role="tab" aria-controls=""><span>Status</span> <div>{{ leave.status}}</div>
                                             </a>

                                       
                                      </div>

                        </section>
                    </section>


                             
                                  <span style="font-size: 13px;padding-left: 1rem;" class="pull-left">Created {{ leave.created }}</span>
                              

              {% if request.user.is_superuser and request.user.is_staff %}

                    <section class="row">
                      <section class="col col-lg-4 col-sm-12 col-lg-offset-7 text-center">
                        <div class="btn-group btn-group-justified">
                          {%if leave.leave_approved %}
                          <a href="{% url 'dashboard:userleaveunapprove' leave.id %}" class="btn btn-success" name='unapprove'>UNAPPROVE
                          </a>
                          {% else %}
                          <a href="{% url 'dashboard:userleaveapprove' leave.id %}" class="btn btn-success" name='approve'>APPROVE
                          </a>
                          {% endif %}
                          <a href="{% url 'dashboard:userleavecancel' leave.id %}" class="btn btn-success" name='cancel'>CANCEL</a>
                          <a href="{% url 'dashboard:reject' leave.id %}" class="btn btn-warning" name='reject'>REJECT</a>  
                        </div>
                      </section>
                    </section>

              {% endif %}

                </section>

            </section> <!-- /container --> 
        </section>
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}

{% endblock %}
</script>